connections:
  # database: oracle
  - name: oracle1dev
    type: oracle
    host: oracle1dev-url
    user: oracle
    database: oracle1dev
    timezone: Asia/Taipei
  - name: mariadb1dev
    type: mariadb
    host: mariadb1dev-url
    user: mariadb
    database: mariadb1dev
    timezone: Asia/Taipei
  - name: s3-minio
    type: s3
    site: tst
    user: minio
    bucket: minio-bucket
    prefix: "'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH"

pipelines:
  - type: cdc
    source: oracle1dev
    sink: mariadb1dev
    sync-collections:
      - from: SCHEMA1.TABLE1
        to: TABLE1
      - from: SCHEMA1.TABLE2
        to: TABLE2
      - from: SCHEMA1.TABLE3
        to: TABLE3
  - type: batch
    source: oracle1dev
    sink: mariadb1dev
    mode: "bulk"
    poll_interval_ms: 3155760000000 # 100 years
    
