---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: dev
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: api
    protocol: TCP
  - port: 9090
    name: console
    protocol: TCP
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: dev
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address :9090
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9090
          name: console
        volumeMounts:
        - mountPath: /data
          name: minio-data
  volumeClaimTemplates:
  - metadata:
      name: minio-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
