version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8.0-debian-11-r36
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: bitnami/kafka:3.3.1-debian-11-r1
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  # mysql:
  #   image: bitnami/mysql:8.0.31-debian-11-r0
  #   ports:
  #    - 3306:3306
  #   environment:
  #    - MYSQL_ROOT_PASSWORD=debezium
  #    - MYSQL_USER=mysqluser
  #    - MYSQL_PASSWORD=mysqlpw 
  mariadb:
    image: bitnami/mariadb:10.6.10-debian-11-r6
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=mybb
      - MYSQL_USER=mybb
      - MYSQL_PASSWORD=changeme
  connect:
    image: omygod613/cp-kafka-connect:6.1.8-20221116
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
     - mariadb
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses