-- Create Debezium CDC user in CDB (Oracle XE 21c)
-- Run as: sqlplus sys/oracle@localhost:1521/XE as sysdba

SET ECHO OFF
SET FEEDBACK OFF
WHENEVER SQLERROR CONTINUE

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Drop existing user if exists
BEGIN
  EXECUTE IMMEDIATE 'DROP USER c##dbzcdc CASCADE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Create common user with CONTAINER=ALL
CREATE USER c##dbzcdc IDENTIFIED BY dbz DEFAULT TABLESPACE users QUOTA UNLIMITED ON users CONTAINER=ALL;

-- Grant LogMiner and CDC privileges
GRANT CONNECT, RESOURCE, DBA TO c##dbzcdc CONTAINER=ALL;
GRANT CREATE SESSION TO c##dbzcdc CONTAINER=ALL;
GRANT SET CONTAINER TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO c##dbzcdc CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO c##dbzcdc CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##dbzcdc CONTAINER=ALL;
GRANT LOGMINING TO c##dbzcdc CONTAINER=ALL;
GRANT CREATE TABLE TO c##dbzcdc CONTAINER=ALL;
GRANT LOCK ANY TABLE TO c##dbzcdc CONTAINER=ALL;
GRANT CREATE SEQUENCE TO c##dbzcdc CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO c##dbzcdc CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$THREAD TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$PARAMETER TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$NLS_PARAMETERS TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$TIMEZONE_NAMES TO c##dbzcdc CONTAINER=ALL;

EXIT;
