-- Oracle XE 21c setup for Debezium CDC test
-- SID: XE, PDB: XEPDB1
-- Run as: sqlplus sys/oracle@localhost:1521/XE as sysdba
--
-- IMPORTANT: Before running this script, ensure ARCHIVELOG mode is enabled:
--   SHUTDOWN IMMEDIATE;
--   STARTUP MOUNT;
--   ALTER DATABASE ARCHIVELOG;
--   ALTER DATABASE OPEN;
--   ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
--   ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

SET ECHO OFF
SET FEEDBACK OFF
WHENEVER SQLERROR CONTINUE

-- Create Debezium common user in CDB
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

DECLARE
  user_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO user_exists FROM all_users WHERE username = 'C##DBZCDC';
  IF user_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER c##dbzcdc IDENTIFIED BY dbz DEFAULT TABLESPACE users QUOTA UNLIMITED ON users CONTAINER=ALL';
  END IF;
END;
/

-- Grant LogMiner privileges for CDC
GRANT CONNECT, RESOURCE, DBA TO c##dbzcdc CONTAINER=ALL;
GRANT CREATE SESSION TO c##dbzcdc CONTAINER=ALL;
GRANT SET CONTAINER TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO c##dbzcdc CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO c##dbzcdc CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##dbzcdc CONTAINER=ALL;
GRANT LOGMINING TO c##dbzcdc CONTAINER=ALL;
GRANT CREATE TABLE TO c##dbzcdc CONTAINER=ALL;
GRANT LOCK ANY TABLE TO c##dbzcdc CONTAINER=ALL;
GRANT CREATE SEQUENCE TO c##dbzcdc CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO c##dbzcdc CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$THREAD TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$PARAMETER TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$NLS_PARAMETERS TO c##dbzcdc CONTAINER=ALL;
GRANT SELECT ON V_$TIMEZONE_NAMES TO c##dbzcdc CONTAINER=ALL;

-- Switch to PDB
ALTER SESSION SET CONTAINER=XEPDB1;

-- Create DEMO schema
DECLARE
  user_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO user_exists FROM all_users WHERE username = 'DEMO';
  IF user_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER DEMO IDENTIFIED BY demo123 DEFAULT TABLESPACE users QUOTA UNLIMITED ON users';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO DEMO';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO DEMO';
  END IF;
END;
/

-- Drop table if exists
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DEMO.SOURCE_ORDERS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Create source table
CREATE TABLE DEMO.SOURCE_ORDERS (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    ORDER_NO VARCHAR2(50) NOT NULL,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    AMOUNT NUMBER(15,2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Enable supplemental logging
ALTER TABLE DEMO.SOURCE_ORDERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Insert test data
INSERT INTO DEMO.SOURCE_ORDERS(ID, ORDER_NO, CUSTOMER_NAME, AMOUNT, STATUS) VALUES(1, 'ORD-001', 'Alice', 1500.00, 'PENDING');
INSERT INTO DEMO.SOURCE_ORDERS(ID, ORDER_NO, CUSTOMER_NAME, AMOUNT, STATUS) VALUES(2, 'ORD-002', 'Bob', 2300.50, 'COMPLETED');
INSERT INTO DEMO.SOURCE_ORDERS(ID, ORDER_NO, CUSTOMER_NAME, AMOUNT, STATUS) VALUES(3, 'ORD-003', 'Charlie', 890.00, 'PENDING');
INSERT INTO DEMO.SOURCE_ORDERS(ID, ORDER_NO, CUSTOMER_NAME, AMOUNT, STATUS) VALUES(4, 'ORD-004', 'Diana', 4200.75, 'SHIPPED');
COMMIT;

EXIT;
