-- Enable ARCHIVELOG mode for Oracle XE 21c
-- This is required for Debezium LogMiner CDC

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER PLUGGABLE DATABASE ALL OPEN;

-- Verify
SELECT LOG_MODE FROM V$DATABASE;

EXIT;
