-- Oracle PDB setup for Debezium CDC test
-- Run as: sqlplus sys/oracle@localhost:1521/ORCLPDB1 as sysdba

SET ECHO OFF
SET FEEDBACK OFF
WHENEVER SQLERROR CONTINUE

-- Create DEMO user (ignore if exists)
DECLARE
  user_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO user_exists FROM all_users WHERE username = 'DEMO';
  IF user_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER DEMO IDENTIFIED BY demo123 DEFAULT TABLESPACE users QUOTA UNLIMITED ON users';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO DEMO';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO DEMO';
  END IF;
END;
/

-- Drop table if exists for clean state
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DEMO.SOURCE_ORDERS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Create source table
CREATE TABLE DEMO.SOURCE_ORDERS (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    ORDER_NO VARCHAR2(50) NOT NULL,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    AMOUNT NUMBER(15,2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Enable supplemental logging (required for CDC)
ALTER TABLE DEMO.SOURCE_ORDERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Insert test data
INSERT INTO DEMO.SOURCE_ORDERS(ID, ORDER_NO, CUSTOMER_NAME, AMOUNT, STATUS) VALUES(1, 'ORD-001', 'Alice', 1500.00, 'PENDING');
INSERT INTO DEMO.SOURCE_ORDERS(ID, ORDER_NO, CUSTOMER_NAME, AMOUNT, STATUS) VALUES(2, 'ORD-002', 'Bob', 2300.50, 'COMPLETED');
INSERT INTO DEMO.SOURCE_ORDERS(ID, ORDER_NO, CUSTOMER_NAME, AMOUNT, STATUS) VALUES(3, 'ORD-003', 'Charlie', 890.00, 'PENDING');
INSERT INTO DEMO.SOURCE_ORDERS(ID, ORDER_NO, CUSTOMER_NAME, AMOUNT, STATUS) VALUES(4, 'ORD-004', 'Diana', 4200.75, 'SHIPPED');
COMMIT;

EXIT;
